import {
  AdminActionButton,
  AdminBadge,
  AdminEmptyState,
  AdminField,
  AdminFilterGrid,
  AdminLinkButton,
  AdminPage,
  AdminPageHeader,
  AdminPagination,
  AdminPanel,
  AdminSectionHeader,
  AdminSelect,
  AdminToolbar,
} from "@/components/admin/workspace";
import { requirePermission } from "@/lib/auth/guards";
import { PERMISSIONS } from "@/lib/auth/permissions";
import { connectToDatabase } from "@/lib/db/mongodb";
import { formatDateTime } from "@/lib/utils/format";
import {
  clampPage,
  readNumberParam,
  readSearchParam,
  type AdminSearchParams,
} from "@/modules/admin/admin-query";
import { NotificationModel } from "@/modules/content/content.models";
import { UserModel } from "@/modules/users/user.model";

type NotificationsPageProps = {
  searchParams: Promise<AdminSearchParams>;
};

const PAGE_SIZE = 20;

function escapeRegex(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export default async function DashboardNotificationsPage({
  searchParams,
}: NotificationsPageProps) {
  const user = await requirePermission(PERMISSIONS.dashboardView);
  const resolvedSearchParams = await searchParams;

  await connectToDatabase();

  const query = readSearchParam(resolvedSearchParams, "q").trim();
  const channel = readSearchParam(resolvedSearchParams, "channel").trim();
  const state = readSearchParam(resolvedSearchParams, "state").trim();
  const requestedPage = readNumberParam(resolvedSearchParams, "page", 1);
  const filter: Record<string, unknown> = {};

  if (user.role === "CUSTOMER") {
    filter.userId = user.id;
  }

  if (channel) {
    filter.channel = channel;
  }

  if (state === "unread") {
    filter.isRead = false;
  } else if (state === "read") {
    filter.isRead = true;
  }

  if (query) {
    const regex = new RegExp(escapeRegex(query), "i");
    filter.$or = [{ title: regex }, { body: regex }, { type: regex }];
  }

  const total = await NotificationModel.countDocuments(filter).exec();
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const safePage = clampPage(requestedPage, totalPages);
  const rows = (await NotificationModel.find(filter)
    .sort({ sentAt: -1, _id: -1 })
    .skip((safePage - 1) * PAGE_SIZE)
    .limit(PAGE_SIZE)
    .lean()
    .exec()) as Array<{
    _id: unknown;
    userId?: unknown;
    channel?: string;
    type?: string;
    title?: string;
    body?: string;
    isRead?: boolean;
    sentAt?: Date;
    relatedType?: string;
    relatedId?: unknown;
  }>;

  const userIds = rows
    .map((row) => String(row.userId ?? ""))
    .filter(Boolean);
  const users = userIds.length
    ? ((await UserModel.find({ _id: { $in: userIds } })
        .select("fullName email")
        .lean()
        .exec()) as Array<{ _id: unknown; fullName?: string; email?: string }>)
    : [];
  const userMap = new Map(
    users.map((entry) => [
      String(entry._id),
      {
        fullName:
          typeof entry.fullName === "string" && entry.fullName.trim()
            ? entry.fullName
            : "User",
        email:
          typeof entry.email === "string" && entry.email.trim() ? entry.email : null,
      },
    ]),
  );

  const unreadCount = await NotificationModel.countDocuments({
    ...(user.role === "CUSTOMER" ? { userId: user.id } : {}),
    isRead: false,
  }).exec();

  return (
    <AdminPage>
      <AdminPageHeader
        title="Notifications"
        description={
          user.role === "CUSTOMER"
            ? "Review the in-app updates tied to your orders, payments, and delivery milestones."
            : "Inspect real notification records generated by order, payment, shipment, return, and refund workflows."
        }
        meta={<AdminBadge label={`${total} total`} tone="sky" />}
      />

      <AdminToolbar>
        <form action="/dashboard/notifications" className="space-y-3" method="get">
          <AdminFilterGrid className="xl:grid-cols-[1.4fr_0.8fr_0.8fr]">
            <AdminField
              defaultValue={query}
              label="Search"
              name="q"
              placeholder="Title, body, or notification type"
            />
            <AdminSelect
              defaultValue={channel}
              label="Channel"
              name="channel"
              options={[
                { value: "", label: "All channels" },
                { value: "IN_APP", label: "IN_APP" },
                { value: "EMAIL", label: "EMAIL" },
                { value: "SMS", label: "SMS" },
              ]}
            />
            <AdminSelect
              defaultValue={state}
              label="State"
              name="state"
              options={[
                { value: "", label: "All states" },
                { value: "unread", label: "Unread" },
                { value: "read", label: "Read" },
              ]}
            />
          </AdminFilterGrid>
          <div className="flex flex-wrap gap-3">
            <AdminActionButton>Apply filters</AdminActionButton>
            <AdminLinkButton href="/dashboard/notifications">Reset</AdminLinkButton>
          </div>
        </form>
      </AdminToolbar>

      <AdminPanel>
        <AdminSectionHeader
          title="Notification feed"
          description={`${unreadCount.toLocaleString("en")} unread notification${unreadCount === 1 ? "" : "s"} in scope.`}
        />

        <div className="mt-4 space-y-3">
          {rows.length > 0 ? (
            rows.map((row) => {
              const recipient = userMap.get(String(row.userId ?? ""));

              return (
                <div
                  className="rounded-[1.4rem] border border-stone-200 bg-white px-4 py-4"
                  key={String(row._id)}
                >
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-slate-950">
                        {row.title ?? "Notification"}
                      </p>
                      <p className="mt-1 text-xs uppercase tracking-[0.16em] text-stone-500">
                        {row.type ?? "EVENT"}
                      </p>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      <AdminBadge label={row.channel ?? "IN_APP"} tone="slate" />
                      <AdminBadge label={row.isRead ? "READ" : "UNREAD"} tone={row.isRead ? "slate" : "amber"} />
                    </div>
                  </div>

                  {row.body ? (
                    <p className="mt-3 text-sm leading-6 text-slate-700">{row.body}</p>
                  ) : null}

                  <div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-stone-500">
                    {recipient ? (
                      <span>
                        {recipient.fullName}
                        {recipient.email ? ` · ${recipient.email}` : ""}
                      </span>
                    ) : null}
                    <span>{formatDateTime(row.sentAt ?? null)}</span>
                    {row.relatedType ? (
                      <span>
                        {row.relatedType}
                        {row.relatedId ? ` · ${String(row.relatedId)}` : ""}
                      </span>
                    ) : null}
                  </div>
                </div>
              );
            })
          ) : (
            <AdminEmptyState
              title="No notifications found"
              body="Notifications generated by real workflows will appear here."
            />
          )}
        </div>

        <div className="mt-4">
          <AdminPagination
            hrefBuilder={(nextPage) => {
              const params = new URLSearchParams();
              if (query) params.set("q", query);
              if (channel) params.set("channel", channel);
              if (state) params.set("state", state);
              params.set("page", String(nextPage));
              return `/dashboard/notifications?${params.toString()}`;
            }}
            page={safePage}
            totalPages={totalPages}
          />
        </div>
      </AdminPanel>
    </AdminPage>
  );
}
